development:
  adapter: postgresql
  encoding: unicode
  database: sushiplate-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sushiplate-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sushiplate-prod
  pool: 5
  host: localhost
  username: action
  password: