# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a65cf28203468c585a2023dfc49e81bf01d22155c39a3c81e5ee21b09d6123149827c7002a18401867bd99576b68acfea2069a35b6837e4d443dc078731531

test:
  secret_key_base: 58a29c35b04fbabf12ced84ba317fbc14b1a4cd1c49a0bb56e89dc4f3cdb5b2748193ff87ca5ba501554e53f1a47b9e4cef6370407b0c152c199822bfd05e6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
